language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - rbx-19mode
script: bundle exec rspec spec
before_script:
  - mysql -e 'create database dossier_test;'
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - cp spec/fixtures/db/mysql2.yml.travis    spec/fixtures/db/mysql2.yml
  - cp spec/fixtures/db/sqlite3.yml.travis   spec/fixtures/db/sqlite3.yml
