language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.2"
env:
  - "RAILS_VERSION=3.2.17"
  - "RAILS_VERSION=4.0.4"
  - "RAILS_VERSION=4.1.0"
script: bundle exec rspec spec
before_script:
  - mysql -e 'create database dossier_test;'
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - cp spec/fixtures/db/mysql2.yml.travis    spec/fixtures/db/mysql2.yml
  - cp spec/fixtures/db/sqlite3.yml.travis   spec/fixtures/db/sqlite3.yml
